### ISSUE TITLE
[Build Error] auro-alert cannot resolve ./src/auro-alert from 2.0.4

### ISSUE THREAD

**Issue by gusnaughton** [AlaskaAirlines/auro-alert#39]
### Please verify the version of auro-alert you have installed

2.0.4

### Please describe the bug

```
error during build:
RollupError: Could not resolve "./src/auro-alert" from "node_modules/@aurodesignsystem/auro-alert/index.js"
    at error (file:///Users/gus.naughtonalaskaair.com/git/flightstatus-web-svelte/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.handleInvalidResolvedId (file:///Users/gus.naughtonalaskaair.com/git/flightstatus-web-svelte/node_modules/rollup/dist/es/shared/node-entry.js:24654:24)
    at file:///Users/gus.naughtonalaskaair.com/git/flightstatus-web-svelte/node_modules/rollup/dist/es/shared/node-entry.js:24616:26 
```

Indeed, there is no src folder distributed with the npm package:
![image](https://github.com/AlaskaAirlines/auro-alert/assets/7005799/f0269d56-1d59-4578-9c4b-265e4ec75eec)

To reproduce:
Node V18.16.0 OS X
```
cd /tmp
mkdir alert-issue
cd alert-issue
cat >> package.json << 'EOF'
{
  "name": "svelte-app",
  "version": "1.0.0",
  "scripts": {
		"build": "vite build",
		"dev": "vite dev --port 8080",
    "start": "vite preview",
		"check": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json",
		"check:watch": "svelte-kit sync && svelte-check --tsconfig ./jsconfig.json --watch",
		"lint": "prettier --plugin-search-dir . --check .",
		"format": "prettier --plugin-search-dir . --write .",
		"storybook": "storybook dev -p 6006",
		"build-storybook": "storybook build"
  },
  "devDependencies": {
		"@fontsource/fira-mono": "^4.5.10",
		"@neoconfetti/svelte": "^1.0.0",
		"@storybook/addon-essentials": "^7.0.20",
		"@storybook/addon-interactions": "^7.0.20",
		"@storybook/addon-links": "^7.0.20",
		"@storybook/blocks": "^7.0.20",
		"@storybook/svelte": "^7.0.20",
		"@storybook/sveltekit": "^7.0.20",
		"@storybook/testing-library": "^0.0.14-next.2",
		"@sveltejs/adapter-auto": "^2.0.0",
		"@sveltejs/kit": "^1.5.0",
		"@types/cookie": "^0.5.1",
		"prettier": "^2.8.0",
		"prettier-plugin-svelte": "^2.8.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"svelte": "^3.54.0",
		"svelte-check": "^3.0.1",
		"typescript": "^5.0.0",
		"vite": "^4.3.0",
		"vitest": "^0.25.3"
  },
  "overrides":{
    "ansi-regex": "^4.1.1",
    "glob-parent": "^5.1.2",
    "got": "^12.1.0",
    "http-cache-semantics": "^4.1.1",
    "node-notifier": "^9.0.0",
    "y18n": "^4.0.1"
  },  
  "type": "module",
  "dependencies": {
		"@alaskaairux/auro-accordion": "^1.3.1",
		"@alaskaairux/auro-checkbox": "^1.2.2",
		"@alaskaairux/auro-flightline": "^1.4.0",
		"@alaskaairux/auro-icon": "^3.4.2",
		"@alaskaairux/auro-interruption": "^1.3.3",
		"@alaskaairux/auro-radio": "^1.6.2",
		"@alaskaairux/design-tokens": "^3.14.0",
		"@aurodesignsystem/auro-alert": "^2.0.3",
		"@aurodesignsystem/auro-avatar": "^4.1.0",
		"@aurodesignsystem/auro-button": "^7.0.1",
		"@aurodesignsystem/auro-flight": "^2.2.0",
		"@aurodesignsystem/auro-header": "^2.0.1",
		"@aurodesignsystem/auro-hyperlink": "^3.3.3",
		"@aurodesignsystem/auro-input": "^2.14.1",
		"@aurodesignsystem/webcorestylesheets": "^4.5.0",
		"@aurolabs/auro-flightstatus": "^1.0.0",
		"@sveltejs/adapter-node": "^1.2.4",
		"airport-codes": "^1.0.2",
		"dotenv": "^16.1.4",
		"jwt-decode": "^3.1.2",
		"moment": "^2.29.4",
		"storybook": "^7.0.20"
  }
}

EOF
npm i
npm run build
```

### Reproducing the error

This issue cannot be reproduced on the Auro docsite

### Expected behavior

2.0.4 should be installable.

Changing to 2.0.3 resolves the issue:
```
		"@aurodesignsystem/auro-alert": "2.0.3",

```

**Comment by blackfalcon** [comment]
Resolved https://github.com/AlaskaAirlines/auro-alert/commit/70d1de08f61d2bf0c1353ba9f92d16376e5c3bc0
